all:
    hosts:
        node1:
        
            ansible_host: 158.160.166.28
            ip: 192.168.30.11
            access_ip: 192.168.30.11
            ansible_user: ubuntu
            ansible_ssh_common_args: "-i /root/.ssh/id_rsa"
        
        
        node2:
            ansible_host: 158.160.96.21
            ip: 192.168.10.9
            access_ip: 192.168.10.9
            ansible_user: ubuntu
            ansible_ssh_common_args: "-i /root/.ssh/id_rsa"
        
        node3:
            ansible_host: 158.160.15.246
            ip: 192.168.20.33
            access_ip: 192.168.20.33
            ansible_user: ubuntu
            ansible_ssh_common_args: "-i /root/.ssh/id_rsa"
        
    children:
        kube_control_plane:
            hosts:
                node1:
        kube_node:
            hosts:
                node2:
                node3:
        etcd:
            hosts:
                node1:
        k8s_cluster:
            children:
                kube_control_plane:
                kube_node:
        calico_rr:
            hosts: {}
    vars:
        supplementary_addresses_in_ssl_keys:
                - "158.160.166.28"
        