all:
    hosts:
        node1:
        
            ansible_host: 158.160.173.96
            ip: 192.168.30.3
            access_ip: 192.168.30.3
            ansible_user: ubuntu
            ansible_ssh_common_args: "-i /root/.ssh/id_rsa"
        
        
        node2:
            ansible_host: 178.154.229.12
            ip: 192.168.10.32
            access_ip: 192.168.10.32
            ansible_user: ubuntu
            ansible_ssh_common_args: "-i /root/.ssh/id_rsa"
        
        node3:
            ansible_host: 158.160.91.170
            ip: 192.168.20.7
            access_ip: 192.168.20.7
            ansible_user: ubuntu
            ansible_ssh_common_args: "-i /root/.ssh/id_rsa"
        
    children:
        kube_control_plane:
            hosts:
                node1:
        kube_node:
            hosts:
                node2:
                node3:
        etcd:
            hosts:
                node1:
        k8s_cluster:
            children:
                kube_control_plane:
                kube_node:
        calico_rr:
            hosts: {}
    vars:
        supplementary_addresses_in_ssl_keys:
                - "158.160.173.96"
        